---
- name: Hello Events
  hosts: all
  sources:
    - ansible.eda.websocket:
        port 8500
  rules:
    - name: Say Hello
      condition: event.i == 1
      action:
        run_playbook:
          name: ansible.eda.hello
...
